name 'nginx-helloworld-m'
maintainer 'Marcelo Mandolesi'
maintainer_email 'mmandolesi@gmail.com'
license 'All rights reserved'
description 'Installs/Configures nginx with a basic helloworld website'
long_description 'Manual install of nginx and site'
version '0.1.0'
source_url 'https://github.com/chef-cookbooks/something'
issues_url 'https://github.com/chef-cookbooks/something/issues'
